# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

# Install system dependencies for pymssql
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    freetds-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY README.md .
COPY src ./src
COPY main.py .

# Install Python dependencies and package
RUN pip install --no-cache-dir .

# Default command
CMD ["mssql-mcp-server"]
